Document: bliss
Title: Debian bliss Manual
Author: <insert document author here>
Abstract: This manual describes what bliss is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bliss/bliss.sgml.gz

Format: postscript
Files: /usr/share/doc/bliss/bliss.ps.gz

Format: text
Files: /usr/share/doc/bliss/bliss.text.gz

Format: HTML
Index: /usr/share/doc/bliss/html/index.html
Files: /usr/share/doc/bliss/html/*.html
